/argument:
  ros__parameters:
    max: 30
    min: 0
    use_sim_time: false

/calculator:
  ros__parameters:
    use_sim_time: false

/operator:
  ros__parameters:
    service_time: 5
    use_sim_time: false